import os

DB_NAME = os.environ["ARANGO_BASE_DB_NAME"]
ARANGO_USER = os.environ["ARANGO_USER"]
ARANGO_PASSWORD = os.environ["ARANGO_ROOT_PASSWORD"]
ARANGO_HOST = f"http://{os.environ['ARANGO_HOST']}:{os.environ['ARANGO_PORT']}"
DEFAULT_MATCH_URL = os.environ["MATCH_FILES_URL"]
SEGMENT_FILES_URL = os.environ["SEGMENT_FILES_URL"]

# METADATA_SCHEMAS = METADATA_DIR + "schemas/"

LANG_TIBETAN = "bo"
LANG_SANSKRIT = "sa"
LANG_CHINESE = "zh"
LANG_PALI = "pa"


DEFAULT_LANGS = (
    LANG_CHINESE,
    LANG_SANSKRIT,
    LANG_TIBETAN,
    LANG_PALI,
)

COLLECTION_PARALLELS = "parallels"
COLLECTION_PARALLELS_SORTED_BY_FILE = "parallels_sorted_file"
COLLECTION_SEGMENTS = "segments"
COLLECTION_SEGMENTS_PAGES = "segments_pages"
COLLECTION_LANGUAGES = "languages"
COLLECTION_FILES = "files"
COLLECTION_METADATA = "metadata"
COLLECTION_CATEGORY_NAMES = "category_names"
COLLECTION_COLLECTION_NAMES = "collection_names"

SA_SEGMENT_URL = SEGMENT_FILES_URL + "dharmanexus-sanskrit/"
BO_SEGMENT_URL = SEGMENT_FILES_URL + "dharmanexus-tibetan/"
ZH_SEGMENT_URL = SEGMENT_FILES_URL + "dharmanexus-chinese/"
PA_SEGMENT_URL = SEGMENT_FILES_URL + "dharmanexus-pali/"

SA_METADATA_URL = SA_SEGMENT_URL + "SA_files.json"
BO_METADATA_URL = BO_SEGMENT_URL + "BO_files.json"
ZH_METADATA_URL = ZH_SEGMENT_URL + "ZH_files.json"
PA_METADATA_URL = PA_SEGMENT_URL + "PA_files.json"

SA_CATEGORY_NAMES_URL = SA_SEGMENT_URL + "SA_category-names.json"
BO_CATEGORY_NAMES_URL = BO_SEGMENT_URL + "BO_category-names.json"
ZH_CATEGORY_NAMES_URL = ZH_SEGMENT_URL + "ZH_category-names.json"
PA_CATEGORY_NAMES_URL = PA_SEGMENT_URL + "PA_category-names.json"

SA_COLLECTION_NAMES_URL = SA_SEGMENT_URL + "SA_collection-names.json"
BO_COLLECTION_NAMES_URL = BO_SEGMENT_URL + "BO_collection-names.json"
ZH_COLLECTION_NAMES_URL = ZH_SEGMENT_URL + "ZH_collection-names.json"
PA_COLLECTION_NAMES_URL = PA_SEGMENT_URL + "PA_collection-names.json"

SEGMENT_URLS = {
    LANG_SANSKRIT: SA_SEGMENT_URL,
    LANG_TIBETAN: BO_SEGMENT_URL,
    LANG_CHINESE: ZH_SEGMENT_URL,
    LANG_PALI: PA_SEGMENT_URL,
}

CATEGORY_NAMES_URLS = {
    LANG_SANSKRIT: SA_CATEGORY_NAMES_URL,
    LANG_TIBETAN: BO_CATEGORY_NAMES_URL,
    LANG_CHINESE: ZH_CATEGORY_NAMES_URL,
    LANG_PALI: PA_CATEGORY_NAMES_URL,
}

COLLECTION_NAMES_URLS = {
    LANG_SANSKRIT: SA_COLLECTION_NAMES_URL,
    LANG_TIBETAN: BO_COLLECTION_NAMES_URL,
    LANG_CHINESE: ZH_COLLECTION_NAMES_URL,
    LANG_PALI: PA_COLLECTION_NAMES_URL,
}

METADATA_URLS = {
    LANG_SANSKRIT: SA_METADATA_URL,
    LANG_TIBETAN: BO_METADATA_URL,
    LANG_CHINESE: ZH_METADATA_URL,
    LANG_PALI: PA_METADATA_URL,
}

COLLECTION_NAMES = (
    COLLECTION_PARALLELS,
    COLLECTION_PARALLELS_SORTED_BY_FILE,
    COLLECTION_SEGMENTS,
    COLLECTION_SEGMENTS_PAGES,
    COLLECTION_LANGUAGES,
    COLLECTION_METADATA,
    COLLECTION_CATEGORY_NAMES,
    COLLECTION_COLLECTION_NAMES,
    COLLECTION_FILES,
)

PAGE_SIZE = 100

MATCH_LIMIT = 1000000
